# Generated by Django 4.1.1 on 2022-09-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TestModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time_1", models.DateTimeField()),
                ("date_time_2", models.DateTimeField()),
            ],
        ),
    ]
